'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ArticleContributor
    Public Property ID As Integer
    Public Property Article_ID As Integer
    Public Property MediaCode As String
    Public Property ContributorDate As Date
    Public Property ContributorType As String
    Public Property Results As String

End Class
