'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Article
    Public Property ID As Integer
    Public Property Article_Title As String
    Public Property Article_Content As String
    Public Property Article_Type As String
    Public Property Article_ImportDate As Date
    Public Property Article_Pseudonym As String
    Public Property Article_CreateDate As Date
    Public Property Article_MediaUrl As String
    Public Property Article_Opr As String
    Public Property IfContributor As Nullable(Of Boolean)
    Public Property IfDel As Boolean

End Class
