'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class bf_MemberInfo
    Public Property ID As System.Guid
    Public Property MemberInfoCode As String
    Public Property MemberName As String
    Public Property EnglishName As String
    Public Property PYIndex As String
    Public Property MemberInfoClassID As Nullable(Of Integer)
    Public Property VIP As Nullable(Of Integer)
    Public Property Sex As String
    Public Property Birthday As Nullable(Of Date)
    Public Property IDCard As String
    Public Property Address As String
    Public Property Address2 As String
    Public Property CheckAddress1 As Nullable(Of Boolean)
    Public Property CheckAddress2 As Nullable(Of Boolean)
    Public Property Postalcode As String
    Public Property Postalcode2 As String
    Public Property Mobilephone As String
    Public Property wiki_UserCode As String
    Public Property Phone As String
    Public Property Officephone As String
    Public Property Email As String
    Public Property City As String
    Public Property LikeInceptNote As Nullable(Of Boolean)
    Public Property LikeInceptEmail As Nullable(Of Boolean)
    Public Property Remark As String
    Public Property FrameID As Nullable(Of Integer)
    Public Property CreateFrameID As Nullable(Of Integer)
    Public Property Status As Nullable(Of Byte)
    Public Property RefDate As Nullable(Of Date)
    Public Property BuyerDate As Nullable(Of Date)
    Public Property MemberDate As Nullable(Of Date)
    Public Property ExteriorID As String
    Public Property LockFlag As Nullable(Of Boolean)
    Public Property CreateID As Nullable(Of Integer)
    Public Property CreateDate As Nullable(Of Date)
    Public Property ModifyID As Nullable(Of Integer)
    Public Property ModifyDate As Nullable(Of Date)
    Public Property ImportFlag As Nullable(Of Integer)
    Public Property ExportFlag As Nullable(Of Integer)
    Public Property DelFlag As Nullable(Of Boolean)
    Public Property HQFlag As Nullable(Of Integer)
    Public Property StoFlag As Nullable(Of Integer)
    Public Property jobs As String
    Public Property titles As String
    Public Property AccountSum As Nullable(Of Decimal)
    Public Property PointSum As Nullable(Of Decimal)

End Class
