'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class bf_wiki_Message
    Public Property ID As System.Guid
    Public Property FromUserName As String
    Public Property ToUserName As String
    Public Property MsgType As String
    Public Property EventName As String
    Public Property Content As String
    Public Property Recognition As String
    Public Property EventKey As String
    Public Property GetTime As Nullable(Of Date)

End Class
