'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class GuestMsg
    Public Property ID As Integer
    Public Property Signed As String
    Public Property IPAddress As String
    Public Property Content As String
    Public Property Contact As String
    Public Property ImputDate As Date
    Public Property IfOpen As Boolean
    Public Property Ifshield As Boolean

End Class
