'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MediaInfo
    Public Property ID As Integer
    Public Property MediaCode As String
    Public Property MediaName As String
    Public Property MediaContact As String
    Public Property Remarks As String

End Class
