'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class PZDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=PZDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property bf_MemberInfo() As DbSet(Of bf_MemberInfo)
    Public Overridable Property bf_wiki_Message() As DbSet(Of bf_wiki_Message)
    Public Overridable Property Advertisements() As DbSet(Of Advertisement)
    Public Overridable Property Articles() As DbSet(Of Article)
    Public Overridable Property ArticleComments() As DbSet(Of ArticleComment)
    Public Overridable Property ArticleContributors() As DbSet(Of ArticleContributor)
    Public Overridable Property ArticleTypes() As DbSet(Of ArticleType)
    Public Overridable Property Competences() As DbSet(Of Competence)
    Public Overridable Property GuestMsgs() As DbSet(Of GuestMsg)
    Public Overridable Property MediaInfoes() As DbSet(Of MediaInfo)
    Public Overridable Property Modules() As DbSet(Of [Module])
    Public Overridable Property Notices() As DbSet(Of Notice)

End Class
