'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class [Module]
    Public Property ID As Integer
    Public Property ModuleName As String
    Public Property ModuleCode As String
    Public Property ModuleType As String
    Public Property ModulePicUrl As String
    Public Property ModuleUrl As String
    Public Property IfEffective As Boolean

End Class
