'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Notice
    Public Property ID As Integer
    Public Property Notice_Title As String
    Public Property Notice_Content As String
    Public Property Notice_ImportDate As Date
    Public Property Notice_Opr As String
    Public Property IfDel As Boolean

End Class
